language: python

install:
  - pip3 install -r tools/Travis-CI/requirements.txt

script:
  - ./tools/Travis-CI/pyIPXACT.run.sh

deploy:
  provider: pypi
  user: "__token__"
  password: $PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
